language: java
jdk: oraclejdk8
before_install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
  - export JAVA_OPTS=-Xmx1280m
  - cd lodmill-rd; sh install-dependencies.sh; cd ..
install:
  - mvn clean install --settings settings.xml
