language: java
jdk: oraclejdk7
before_install:
  - cd lodmill-rd; sh install-dependencies.sh; cd ..
install:
  - mvn clean install -e -q -DskipTests=true -Dmysql.classifier=linux-amd64 --settings settings.xml
script:
  - umask 0022
  - mvn integration-test -Dmysql.classifier=linux-amd64 -e -q --settings settings.xml
